---
title: "Data Anaylsis Project"
output: html_document
date: "2022-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
```
```{r}
Education_Stats <- read_csv("final project/Education Stats - Digest 2018 Table 233.27.csv")
```


```{r}
Education_Stats<-Education_Stats %>% 
  clean_names() 
```




```{r}
Education_Stats %>% 
  select(disability_status_sex_and_race_ethnicity, total, all_expulsions) %>% 
  filter((disability_status_sex_and_race_ethnicity == "Total") | (disability_status_sex_and_race_ethnicity == "D_Total")) %>% 
  mutate(combined = total + all_expulsions)



```

# What is the rate for total suspensions and expulsions combined for all students versus students with disabilities per 1,000 students?

```{r}
#What is the rate of total suspensions to total expulsions? For every expulsion, how many student suspensions are there? 






#How many suspensions or  expulsions do minority children face in comparison to their white counterparts 







