---
title: "Project 1"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(ggplot2)
library(ggthemes)

balt_homeowner <- read_csv("pct_home_owner_bmore.csv")
balt_poverty <- read_csv("pct_pov_bmore.csv")
#balt_homeowner <- read_csv("gg plot assignment/pct_pov_family_bmore.csv")
```

```{r}
#What does the data mean: In the data provided by Baltimore Neighborhood Indicators Alliance, balt_poverty table  measures the percentage of households whose income fell below the poverty threshold out of all households in an area. Baltimore Neighborhood Indicators Alliance took perctange of the population of Baltimore city which is a little over 500,000. The benchmark of poverty are housholds who make less than approximately 20,000.  

# The varibles such hhpov and hhpov16 indicates the Household poverty for that given year 
#the variables variables mean in balt_homeowner such ownroc10 indicate owner occupied housing residents for that given year. CSA stands for  Community Statistical Area. 
```

```{r}
balt_poverty <- clean_names(balt_poverty)
#clean the names on the data 

```
````{r}
#  1 Which year had the highest poverty rate and what neighborhood did that belong to? 
#2015 had the highest percentage rate of poverty in the neighborhood, Poppleton

balt_poverty%>%
  arrange(desc(hhpov15))

balt_poverty%>%
  arrange(desc(hhpov16))

balt_poverty%>%
  arrange(desc(hhpov17))

balt_poverty%>%
  arrange(desc(hhpov18))

balt_poverty%>%
  arrange(desc(hhpov19))
```

```{r}  
# 2What are the average homeownership rates from 2015 to 2019?
# The average homeownership rate from 2015 to 2019 is as follows: 56.1318, ,55.00812,	54.64898,52.63286.
balt_homeowner <- balt_homeowner %>% 
  mutate(city = "Baltimore")

avg_balt_homeowner <- balt_homeowner %>% 
  group_by(city) %>% 
  summarise(
    avg_home_15 = mean(ownroc15, na.rm=TRUE),
    avg_home_16 = mean(ownroc16, na.rm=TRUE),
    avg_home_17 = mean(ownroc17, na.rm=TRUE), 
    avg_home_18 = mean(ownroc18, na.rm=TRUE),
    avg_home_19 = mean(ownroc19, na.rm=TRUE)) %>% 
  view()
```

```{r}
#3:  What was the average poverty rate in 2019 and which neighborhoods were above that(meaning they have a higher poverty rate than the average)?

#3:The average poverty rate in 2019 was 16.68425. The neighborhoods below that included Poppleton/The Terraces/Hollins Market, Cherry Hill and Upton/Druid Heights, which had the highest poverty rate. 

balt_poverty <- balt_poverty %>% 
  mutate(city = "Baltimore")

avg_balt_pov <- balt_poverty %>% 
  group_by(city) %>% 
  summarise(
    avg_pov_19 = mean(hhpov19, na.rm=TRUE)
  )

balt_poverty %>% 
  filter(hhpov19 > 16.68425) %>% 
  select(csa2010, hhpov19) %>% 
  arrange(desc(hhpov19)) %>% 
  view()

balt_poverty %>% 
  filter(hhpov18 > 16.68425) %>% 
  select(csa2010, hhpov18) %>% 
  arrange(desc(hhpov18)) %>% 
  view()
```

```{r}
# Take the neighborhoods with the highest poverty rates and compare them to their homeownership rates in 2019 on two bar charts. 

# Create a bar chart showing the comparisons of the relationship  between the poverty rates and the homeownership rates in 2019. 

top_10_pov <- balt_poverty %>% 
  select(csa2010, hhpov19) %>% 
  arrange(desc(hhpov19)) %>% 
  slice_max(hhpov19, n=10)

pov_neighborhoods_homeowner <- balt_homeowner %>% 
  select(CSA2010, ownroc19) %>% 
  filter(
    CSA2010 == 'Upton/Druid Heights' | CSA2010 == 'Poppleton/The Terraces/Hollins Market' |
    CSA2010 == 'Cherry Hill' | CSA2010 == 'Sandtown-Winchester/Harlem Park' | CSA2010 ==
    'Oldtown/Middle East' | CSA2010 == 'Madison/East End' | CSA2010 == 'Southwest Baltimore' | 
    CSA2010 == 'Southern Park Heights' | CSA2010 == 'Southeastern' | CSA2010 == 'Greater Rosemont'
    ) %>% 
  arrange(desc(ownroc19))

pov_neighborhoods_homeowner %>%
  ggplot() +
  geom_bar(aes(x=reorder(CSA2010, ownroc19), weight=ownroc19)) +
  coord_flip() + 
  theme_minimal() + 
  theme_economist() +
  labs(
    title="Top 10 Neighborhoods with the Highest Poverty Rates in 2019",
    x = "Neighborhoods",
    y = "Poverty Rate",
    caption = "Source: Baltimore Open Data")

top_10_pov %>%
  ggplot() +
  geom_bar(aes(x=reorder(CSA2010, hhpov19), weight=hhpov19)) +
  coord_flip() + 
  theme_minimal() + 
  theme_economist() +
  labs(
    title="Household Ownership of Neighborhoods with the Highest Poverty Rates in 2019",
    x = "Neighborhoods",
    y = "Household Ownership Rate",
    caption = "Baltimore Open Data")
  
# There are 2 charts, the first chart inidcates the neighborhood with highest rates and the second shows the householdownership rates in nieghborhoods with the highest poverty rates. 
```
```{r}
#Reporting memo/pitch: After observing data tables that reviewed the Percent of Family Households Living Below the Poverty Line and Percentage of Housing Units that are Owner-Occupied. 2015 had the highest percentage rate of poverty and he neighborhoods affected were Poppleton, Druid Heights Cherry Hill, and Harlem Park. While cities like Baltimore are commonly known for the lack of economic opportunity, one thing that would be fascinating to learn is why that is and what is prevalent in these neighborhoods and who is responsible.  In addition, I learned the average homeownership has decreased from 2015-2019. In 2015 the average home ownership was 56.1318, while the average home ownership was 52.63286. It would be incredible to learn more about the factors at why it has declined over the years, what city, county,state, or governmental policies influenced this. While the housing crisis was in 2008, 7 years may not have been enough to change the economic downturn. Just a few years later, in 2019, the average poverty rate was at 16.6842. The neighborhoods below that included Poppleton/The Terraces/Hollins Market, Cherry Hill and Upton/Druid Heights, which had the highest poverty rate. 

#tweet 1:Druid heights and Poppleton continue high poverty rates throughout 2015-2019
#tweet 2: Homeownership in neighborhoods such as southern park heights and greater Rosemont continue  to see low trends of homeownership 



``` 


